### ISSUE TITLE
Loaded but does nothing

### ISSUE THREAD

**Issue by nikonakoneko** [jbyuki/ntangle.nvim#3]
I'm using neovim 0.7.2 but I also tried the vim plugin with a bare vim configuration. The filetype isn't set and even if I set it manually there's no coloration or anything :/

I can confirm plugin is loaded by checking packer_plugins global

**Comment by jbyuki** [comment]
The filetype is not set by ntangle.nvim. That's normal. The filetype was set in the previous tangle.vim, as a hack to still have syntax coloring. But it now relies on an external plugin [ntangle-ts.nvim](https://github.com/jbyuki/ntangle-ts.nvim). Installing it will enable syntax coloring.

**Comment by jbyuki** [comment]
Did you succeed in something?

**Comment by nikonakoneko** [comment]
i didnt try yet. i'll tell you as soon as i do

**Comment by jbyuki** [comment]
Ok

**Comment by nikonakoneko** [comment]
I tried with only your plugins and treesitter but nothing happens. I'm unsure if I'm doing something wrong.

Here the result:

![nvim screenshot](https://0x0.st/o1No.png)

And you can reproduce with the following script, passing as argument the init.lua below and somewhere to store runtime data and config dir.

```bash
#!/bin/bash
if [[ -z "$(LC_ALL=C type -t realpath)" ]]
then
    realpath() (
    OURPWD=$PWD
    cd "$(dirname "$1")"
    LINK=$(readlink "$(basename "$1")")
    while [ "$LINK" ]; do
        cd "$(dirname "$LINK")"
        LINK=$(readlink "$(basename "$1")")
    done
    REALPATH="$PWD/$(basename "$1")"
    cd "$OURPWD"
    echo "$REALPATH"
)
fi

if [[ $TERMUX_VERSION ]];
then
    TMPDIR="$TMUX_TMPDIR"
else
    TMPDIR="${TMPDIR:-/tmp}"
fi

if [[ ! -f "$(realpath $1)" ]]
then
    echo "Invalid argument"
    echo "syntax: $0 VIMRC [DIR]"
    echo "VIMRC is the configuration file to use"
    echo "DIR is where runtime and configuration will be stored."
    echo "if not specified a temporary one will be used."
fi

if [[ -z "$2" ]]
then
    NVIM_DIR="$(mktemp --directory hsv2.nvim-test.XXXXXXXX)"
else
    if [[ ! -d "$(realpath $2)" ]]
    then
        mkdir "$2"
    fi
    NVIM_DIR="$2"
fi

export XDG_DATA_HOME="$NVIM_DIR/data"
export XDG_CONFIG_HOME="$NVIM_DIR/conf"
export MYVIMRC="$1"

echo data stored in $NVIM_DIR
nvim -u "$MYVIMRC"
```

with the following configuration:

```lua
-- vim: et sw=4 ts=4:
local function clone_packer()
    local path = vim.fn.stdpath('data') .. '/site/pack/packer/start/packer.nvim'
    if vim.fn.empty(vim.fn.glob(path)) > 0 then
        vim.fn.system {
            'git',
            'clone',
            '--depth=1',
            'https://github.com/wbthomason/packer.nvim',
            path
        }
    end
end

local function bootstrap_packer(pkgs, opts)
    pkgs = pkgs or {}
    opts = opts or {}
    clone_packer()
    -- Load Packer
    vim.cmd('packadd packer.nvim')
    local packer = require('packer')
    packer.startup({ pkgs, opts })
    packer.sync()
end

local pkgs = {
    'wbthomason/packer.nvim',
    'jbyuki/ntangle.nvim',
    'jbyuki/ntangle-ts.nvim',
    {
        'nvim-treesitter/nvim-treesitter',
        run = function()
            require('nvim-treesitter.install').update({ with_sync = true })
        end,
    },
}

bootstrap_packer(pkgs)
```

**Comment by jbyuki** [comment]
I don't see the extension of the file on the top-left but is that a neorg file? To syntax color that, you need to install neorg.nvim probably. My plugins support *.t files such as *.lua.t file, that's a completely different way to program to neorg. Maybe you were looking for something else all along?

**Comment by nikonakoneko** [comment]
My confusion, I got here thinking it was a plugin for Literate (which anyway I was going to drop because of some bugs)
