### ISSUE TITLE
does not catch redefinitions of variables and lua lsp shows param  type mismatch

### ISSUE THREAD

**Issue by matu3ba** [jbyuki/ntangle.nvim#4]
To reproduce, open [b09c2f36ddf70b498281845109bedcf08a7e0de0](https://github.com/jbyuki/venn.nvim/blob/b09c2f36ddf70b498281845109bedcf08a7e0de0/lua/venn/init.lua)
in lua lsp and see what the lsp complains about.

Can provide more details, if needed. However, above instructions should be sufficient to reproduce.

**Comment by jbyuki** [comment]
I'm confused. Are you using LSP inside *.t files? Although I did some attempts in my early days, it is not supported as of now. I'm actively working towards a neovim fork for first class support for such features but it's still work in progress. 

I would be more than happy for support on that project, let me know if you're interested. It involves quite complex data structures and algorithms. In particular incremental tangling which may be similar to incremental compilation. 

So currently I do all my lua plugin programming without LSP and broken highlighting which is, I concede, very suboptimal.

**Comment by matu3ba** [comment]
> I'm confused. Are you using LSP inside *.t files?

No, on the generated file. 

> not supported as of now

kk, thats fine for me. Just wanted to make you aware, because I found no similar issue and support status.

> particular incremental tangling which may be similar to incremental compilation

I don't have currently the capacity for around 1-2 months, but that sounds worthwhile to do as I wanted to write about optimal incremental verification via editor (which I was not allowed to describe + implement in my master thesis) and this might be closely related. Can you pitch me something to read and/or what/where to look for?

> lua plugin programming without LSP and broken highlighting

lua-lsp and the neovim types (from a plugin) are necessary, if you want to have smooth autocompletion. it might be fiddly to setup due to order requirements of things, but its overall okayish.
